title: Yago Boullaude
logo: https://github.com/Yago-Data/Portafolio/blob/main/imagenes/FOTO%20YAGO%20CV%202023.jpeg

description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
